server:
  port: 5555

  #Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

eureka:
  #  instance:
  #    prefer-ip-address: true
  client:
    register-with-eureka: true
    #Pull down a local copy of the registry.
    fetch-registry: true
    service-url:
      defaultZone: ${discovery-server:http://localhost:8889/eureka/}
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  profiles:
    active:
      default
  cloud:
    gateway:
      routes:
        - id: web-app
          uri: lb://web-app
          predicates:
            - Path=/web-app/**
          filters:
            - name: CircuitBreaker
              args:
                name: web-app
                fallbackuri: forward:/webAppServiceFallBack
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/userServiceFallBack

#Hystrix timeout for all of the services running through Zuul
#timeout for specific service - replace the 'default' part
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

# for Spring Boot Actuator endpoint /beans
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
#        include: '*'