server:
  port: 8083

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://127.0.0.1:9411/

#DB properties:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    tomcat:
      validation-query: SELECT 1

  #Hibernate Configuration:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    #Pull down a local copy of the registry.
    fetch-registry: true
    service-url:
      defaultZone: ${discovery-server:http://localhost:8889/eureka/}
  instance:
    hostname: localhost
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}