#DB properties:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    tomcat:
      validation-query: SELECT 1

  #Hibernate Configuration:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true