server:
  servlet:
    context-path: /web-app
  port: 8082

#Register the IP of the service rather than the server name.
eureka:
  instance:
    #Register the IP of the service rather than the server name.
    prefer-ip-address: true
  client:
    register-with-eureka: true
    #Pull down a local copy of the registry.
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8889/eureka/}

#DB properties:
#  datasource:
#    url: jdbc:mysql://localhost:3306/pizzeria?serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#
#    tomcat:
#      validation-query: SELECT 1
#
#  #Hibernate Configuration:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#security:
#  jwt:
#    key-store: classpath:keystore.jks
#    key-store-password: letmein
#    key-pair-alias: mytestkey
#    key-pair-password: changeme
#
#    public-key: classpath:public.txt
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8081/oauth-server/user
      preferTokenInfo: false